/* ════════════════════════════════════════════════════════════
   PRIONSENLIGNE — Concordance thématique de la Bible
   ─────────────────────────────────────────────────────────────
   Index thème → passages bibliques, à la manière des concordances
   thématiques classiques (chaîne Thompson…). Utilisé par la
   recherche de l'onglet Bible (js/bible.js) : taper « pardon »,
   « avortement », « partage »… fait remonter les passages liés.

   Format : { t: titre du thème,
              kw: mots-clés/synonymes (matching sans accents),
              refs: [ [référence parsable, courte description], … ] }

   Les références utilisent les noms de livres EXACTS de BOOKS
   (bible.js) : Genèse, Psaumes, Ésaïe, Ecclésiaste, Cantique,
   1 Corinthiens… Numérotation des Psaumes : hébraïque (LSG).
   ════════════════════════════════════════════════════════════ */

window.PEL_BIBLE_THEMES = [

  // ── Vertus & vie spirituelle ─────────────────────────────
  { t: 'Amour de Dieu et du prochain',
    kw: ['amour', 'aimer', 'charite', 'aime ton prochain'],
    refs: [
      ['Matthieu 22:37',      'Le plus grand commandement : aimer'],
      ['Jean 13:34',          'Aimez-vous les uns les autres'],
      ['1 Corinthiens 13:4',  'L’amour est patient, l’amour est bon'],
      ['1 Jean 4:7',          'L’amour vient de Dieu'],
      ['Romains 13:8',        'L’amour accomplit toute la loi'],
      ['Jean 15:13',          'Donner sa vie pour ceux qu’on aime'],
    ] },
  { t: 'Pardon',
    kw: ['pardon', 'pardonner', 'rancune', 'offense', 'reconciliation'],
    refs: [
      ['Matthieu 18:21',      'Pardonner jusqu’à 70 fois 7 fois'],
      ['Matthieu 6:14',       'Pardonnez et vous serez pardonnés'],
      ['Luc 23:34',           'Père, pardonne-leur (en croix)'],
      ['Éphésiens 4:32',      'Pardonnez-vous comme Dieu vous a pardonné'],
      ['Colossiens 3:13',     'Supportez-vous et pardonnez-vous'],
      ['Luc 15:11',           'Le fils prodigue accueilli par le Père'],
    ] },
  { t: 'Partage et générosité',
    kw: ['partage', 'partager', 'generosite', 'genereux', 'donner', 'don', 'aumone'],
    refs: [
      ['Actes des Apôtres 20:35',         'Il y a plus de bonheur à donner qu’à recevoir'],
      ['Luc 3:11',            'Que celui qui a deux tuniques partage'],
      ['2 Corinthiens 9:7',   'Dieu aime celui qui donne avec joie'],
      ['Matthieu 25:35',      'J’avais faim et vous m’avez nourri'],
      ['Proverbes 19:17',     'Donner au pauvre, c’est prêter à Dieu'],
      ['Actes des Apôtres 2:44',          'La première communauté mettait tout en commun'],
      ['Hébreux 13:16',        'N’oubliez pas la bienfaisance'],
    ] },
  { t: 'Égoïsme',
    kw: ['egoisme', 'egoiste', 'chacun pour soi', 'interet personnel'],
    refs: [
      ['Philippiens 2:3',     'Ne faites rien par égoïsme'],
      ['Luc 12:16',           'Le riche insensé qui amasse pour lui'],
      ['1 Jean 3:17',         'Fermer son cœur à son frère dans le besoin'],
      ['1 Corinthiens 10:24', 'Que personne ne cherche son propre intérêt'],
      ['Jacques 3:16',        'Où il y a un esprit de rivalité, il y a du désordre'],
    ] },
  { t: 'La vie avant la naissance',
    kw: ['avortement', 'ivg', 'embryon', 'foetus', 'sein maternel', 'vie avant la naissance', 'enfant a naitre', 'grossesse'],
    refs: [
      ['Psaumes 139:13',      'Tu m’as tissé dans le sein de ma mère'],
      ['Jérémie 1:5',          'Avant de te former, je te connaissais'],
      ['Luc 1:41',            'L’enfant tressaillit dans le sein d’Élisabeth'],
      ['Job 10:8',            'Tes mains m’ont façonné'],
      ['Isaïe 44:2',           'Celui qui t’a formé dès le ventre maternel'],
      ['Isaïe 49:15',          'Une femme oublie-t-elle l’enfant qu’elle allaite ?'],
      ['Deutéronome 30:19',   'Choisis la vie, afin que tu vives'],
    ] },
  { t: 'Espérance',
    kw: ['esperance', 'espoir', 'esperer', 'desespoir', 'avenir'],
    refs: [
      ['Jérémie 29:11',        'Des projets de paix et non de malheur'],
      ['Romains 15:13',       'Le Dieu de l’espérance vous comble de joie'],
      ['Lamentations 3:22',   'Ses compassions se renouvellent chaque matin'],
      ['Hébreux 6:19',         'L’espérance, ancre de l’âme'],
      ['Psaumes 42:6',        'Espère en Dieu, mon âme abattue'],
      ['Romains 8:24',        'C’est en espérance que nous sommes sauvés'],
    ] },
  { t: 'Foi et confiance',
    kw: ['foi', 'croire', 'confiance en dieu', 'doute', 'douter'],
    refs: [
      ['Hébreux 11:1',         'La foi : l’assurance des choses espérées'],
      ['Marc 9:23',           'Tout est possible à celui qui croit'],
      ['Matthieu 17:20',      'La foi grosse comme une graine de moutarde'],
      ['Jean 20:29',          'Heureux ceux qui croient sans avoir vu'],
      ['Proverbes 3:5',       'Confie-toi en l’Éternel de tout ton cœur'],
      ['Jacques 2:17',        'La foi sans les œuvres est morte'],
    ] },
  { t: 'Prière',
    kw: ['priere', 'prier', 'intercession', 'comment prier'],
    refs: [
      ['Matthieu 6:9',        'Le Notre Père, modèle de toute prière'],
      ['Matthieu 7:7',        'Demandez et l’on vous donnera'],
      ['Philippiens 4:6',     'En toute chose, priez avec actions de grâces'],
      ['1 Thessaloniciens 5:17', 'Priez sans cesse'],
      ['Luc 18:1',            'Prier toujours, sans se décourager'],
      ['Jacques 5:16',        'La prière du juste a une grande efficacité'],
    ] },
  { t: 'Louange et adoration',
    kw: ['louange', 'louer', 'adoration', 'adorer', 'chanter dieu'],
    refs: [
      ['Psaumes 150:1',       'Que tout ce qui respire loue l’Éternel'],
      ['Psaumes 103:1',       'Mon âme, bénis l’Éternel'],
      ['Psaumes 95:1',        'Venez, chantons avec allégresse'],
      ['Éphésiens 5:19',       'Psaumes, hymnes et cantiques spirituels'],
      ['Psaumes 34:2',        'Je bénirai l’Éternel en tout temps'],
      ['Colossiens 3:16',     'Chantez à Dieu dans vos cœurs'],
    ] },
  { t: 'Sagesse et discernement',
    kw: ['sagesse', 'sage', 'discernement', 'discerner', 'decision'],
    refs: [
      ['Jacques 1:5',         'Si quelqu’un manque de sagesse, qu’il la demande'],
      ['Proverbes 9:10',      'La crainte de l’Éternel, commencement de la sagesse'],
      ['Proverbes 4:7',       'Acquiers la sagesse par-dessus tout'],
      ['1 Rois 3:9',          'Salomon demande un cœur qui discerne'],
      ['Ecclésiaste 7:12',    'La sagesse fait vivre ceux qui la possèdent'],
    ] },
  { t: 'Humilité',
    kw: ['humilite', 'humble', 's abaisser', 'modestie'],
    refs: [
      ['Matthieu 11:29',      'Doux et humble de cœur'],
      ['Philippiens 2:3',     'Regardez les autres comme supérieurs à vous'],
      ['Michée 6:8',           'Marcher humblement avec ton Dieu'],
      ['Luc 14:11',           'Qui s’abaisse sera élevé'],
      ['1 Pierre 5:5',        'Dieu fait grâce aux humbles'],
      ['Jean 13:14',          'Jésus lave les pieds de ses disciples'],
    ] },
  { t: 'Patience et persévérance',
    kw: ['patience', 'patient', 'perseverance', 'perseverer', 'endurance', 'tenir bon'],
    refs: [
      ['Jacques 5:7',         'Prenez patience, comme le laboureur'],
      ['Romains 5:3',         'La détresse produit la persévérance'],
      ['Galates 6:9',         'Ne nous lassons pas de faire le bien'],
      ['Hébreux 12:1',         'Courons avec persévérance'],
      ['Psaumes 40:2',        'J’avais mis mon espérance en l’Éternel'],
    ] },
  { t: 'Gratitude et action de grâce',
    kw: ['gratitude', 'merci', 'remercier', 'action de grace', 'reconnaissance'],
    refs: [
      ['1 Thessaloniciens 5:18', 'Rendez grâces en toutes choses'],
      ['Psaumes 103:2',       'N’oublie aucun de ses bienfaits'],
      ['Luc 17:15',           'Le lépreux qui revient dire merci'],
      ['Colossiens 3:17',     'Faites tout en rendant grâces'],
      ['Psaumes 118:1',       'Célébrez l’Éternel car il est bon'],
    ] },
  { t: 'Joie',
    kw: ['joie', 'joyeux', 'bonheur', 'se rejouir'],
    refs: [
      ['Philippiens 4:4',     'Réjouissez-vous toujours dans le Seigneur'],
      ['Néhémie 8:10',         'La joie de l’Éternel est votre force'],
      ['Jean 15:11',          'Que votre joie soit parfaite'],
      ['Psaumes 16:11',       'Plénitude de joie devant ta face'],
      ['Galates 5:22',        'La joie, fruit de l’Esprit'],
      ['Psaumes 118:24',      'Voici le jour que l’Éternel a fait'],
    ] },

  // ── Épreuves & émotions ─────────────────────────────────
  { t: 'Peur et angoisse',
    kw: ['peur', 'angoisse', 'anxiete', 'anxieux', 'inquietude', 'crainte', 'stress'],
    refs: [
      ['Isaïe 41:10',          'Ne crains rien, car je suis avec toi'],
      ['Psaumes 23:4',        'Je ne crains aucun mal, tu es avec moi'],
      ['Jean 14:27',          'Que votre cœur ne se trouble point'],
      ['2 Timothée 1:7',      'Un esprit de force, d’amour et de sagesse'],
      ['Matthieu 14:27',      'Rassurez-vous, c’est moi, n’ayez pas peur'],
      ['Psaumes 27:1',        'De qui aurais-je peur ?'],
      ['1 Pierre 5:7',        'Déchargez-vous sur lui de tous vos soucis'],
    ] },
  { t: 'Souffrance et épreuve',
    kw: ['souffrance', 'souffrir', 'epreuve', 'douleur', 'detresse'],
    refs: [
      ['Romains 8:18',        'Les souffrances présentes et la gloire à venir'],
      ['2 Corinthiens 12:9',  'Ma grâce te suffit'],
      ['Psaumes 34:19',       'Près de ceux qui ont le cœur brisé'],
      ['Jean 16:33',          'Prenez courage, j’ai vaincu le monde'],
      ['Isaïe 53:4',           'Il a porté nos souffrances'],
      ['1 Pierre 5:7',        'Il prend soin de vous'],
    ] },
  { t: 'Maladie et guérison',
    kw: ['maladie', 'malade', 'guerison', 'guerir', 'sante', 'hopital'],
    refs: [
      ['Jacques 5:14',        'Quelqu’un est-il malade ? Qu’on prie pour lui'],
      ['Psaumes 103:3',       'Il guérit toutes tes maladies'],
      ['Isaïe 53:5',           'Par ses meurtrissures nous sommes guéris'],
      ['Marc 5:34',           'Ta foi t’a sauvée, va en paix'],
      ['Jérémie 17:14',        'Guéris-moi, Éternel, et je serai guéri'],
      ['Matthieu 8:2',        'Jésus guérit le lépreux'],
    ] },
  { t: 'Deuil et mort',
    kw: ['deuil', 'mort', 'mourir', 'defunt', 'perte d un proche', 'enterrement', 'funerailles'],
    refs: [
      ['Jean 11:25',          'Je suis la résurrection et la vie'],
      ['Apocalypse 21:4',     'Il essuiera toute larme de leurs yeux'],
      ['1 Thessaloniciens 4:13', 'Ne pas s’affliger comme ceux sans espérance'],
      ['Matthieu 5:4',        'Heureux les affligés, ils seront consolés'],
      ['Romains 14:8',        'Soit que nous vivions, soit que nous mourions'],
      ['Psaumes 116:15',      'La mort de ses fidèles est précieuse à Dieu'],
    ] },
  { t: 'Tristesse et consolation',
    kw: ['tristesse', 'triste', 'consolation', 'consoler', 'chagrin', 'larmes', 'depression'],
    refs: [
      ['Matthieu 11:28',      'Venez à moi, vous qui êtes fatigués'],
      ['2 Corinthiens 1:3',   'Le Dieu de toute consolation'],
      ['Psaumes 147:3',       'Il guérit ceux qui ont le cœur brisé'],
      ['Isaïe 61:2',           'Consoler tous les affligés'],
      ['Jean 16:20',          'Votre tristesse se changera en joie'],
      ['Psaumes 34:19',       'L’Éternel est près des cœurs brisés'],
    ] },
  { t: 'Solitude',
    kw: ['solitude', 'seul', 'isolement', 'isole', 'abandon', 'abandonne'],
    refs: [
      ['Matthieu 28:20',      'Je suis avec vous tous les jours'],
      ['Deutéronome 31:6',    'Il ne te délaissera point'],
      ['Psaumes 27:10',       'Même abandonné de tous, l’Éternel m’accueille'],
      ['Isaïe 43:2',           'Si tu traverses les eaux, je serai avec toi'],
      ['Psaumes 139:7',       'Où fuir loin de ta présence ?'],
      ['Genèse 28:15',        'Je suis avec toi, je te garderai partout'],
    ] },
  { t: 'Courage et force',
    kw: ['courage', 'force', 'fortifier', 'faiblesse', 'decouragement'],
    refs: [
      ['Josué 1:9',           'Fortifie-toi et prends courage'],
      ['Philippiens 4:13',    'Je puis tout par celui qui me fortifie'],
      ['Isaïe 40:31',          'Ils prennent le vol comme les aigles'],
      ['Deutéronome 31:6',    'Fortifiez-vous, ne craignez point'],
      ['Psaumes 27:1',        'L’Éternel est la force de ma vie'],
    ] },
  { t: 'Honte et culpabilité',
    kw: ['honte', 'culpabilite', 'coupable', 'remords', 'se pardonner'],
    refs: [
      ['Romains 8:1',         'Aucune condamnation pour ceux qui sont en Christ'],
      ['Psaumes 32:5',        'Je t’ai avoué mon péché… tu as pardonné'],
      ['1 Jean 3:20',         'Dieu est plus grand que notre cœur'],
      ['Michée 7:19',          'Il jettera nos péchés au fond de la mer'],
      ['Isaïe 54:4',           'Ne crains pas, tu ne seras pas confuse'],
      ['Psaumes 34:6',        'Ceux qui regardent vers lui sont rayonnants'],
    ] },

  // ── Défauts & combat spirituel ──────────────────────────
  { t: 'Colère',
    kw: ['colere', 's emporter', 'irritation', 'enervement', 'fureur'],
    refs: [
      ['Jacques 1:19',        'Lent à parler, lent à la colère'],
      ['Éphésiens 4:26',       'Que le soleil ne se couche pas sur votre colère'],
      ['Proverbes 15:1',      'Une réponse douce calme la fureur'],
      ['Proverbes 16:32',     'Lent à la colère vaut mieux qu’un héros'],
      ['Colossiens 3:8',      'Rejetez colère, animosité, méchanceté'],
    ] },
  { t: 'Jalousie et envie',
    kw: ['jalousie', 'jaloux', 'envie', 'envieux', 'convoitise', 'convoiter'],
    refs: [
      ['Proverbes 14:30',     'L’envie est la carie des os'],
      ['1 Corinthiens 13:4',  'L’amour n’est point envieux'],
      ['Jacques 3:16',        'Où il y a jalousie, il y a désordre'],
      ['Galates 5:26',        'Ne nous envions pas les uns les autres'],
      ['Exode 20:17',         'Tu ne convoiteras point'],
      ['Psaumes 37:1',        'Ne porte pas envie à ceux qui font le mal'],
    ] },
  { t: 'Orgueil',
    kw: ['orgueil', 'orgueilleux', 'fierte', 'vanite', 'pretention', 'arrogance'],
    refs: [
      ['Proverbes 16:18',     'L’arrogance précède la chute'],
      ['Jacques 4:6',         'Dieu résiste aux orgueilleux'],
      ['Luc 18:9',            'Le pharisien et le publicain'],
      ['Matthieu 23:12',      'Quiconque s’élèvera sera abaissé'],
      ['Proverbes 11:2',      'Quand vient l’orgueil, vient aussi l’ignominie'],
    ] },
  { t: 'Mensonge et vérité',
    kw: ['mensonge', 'mentir', 'menteur', 'verite', 'calomnie', 'hypocrisie'],
    refs: [
      ['Jean 8:32',           'La vérité vous rendra libres'],
      ['Proverbes 12:22',     'Les lèvres fausses sont en horreur à l’Éternel'],
      ['Éphésiens 4:25',       'Renoncez au mensonge'],
      ['Exode 20:16',         'Tu ne porteras point de faux témoignage'],
      ['Jean 14:6',           'Je suis le chemin, la vérité et la vie'],
      ['Colossiens 3:9',      'Ne mentez pas les uns aux autres'],
    ] },
  { t: 'Tentation',
    kw: ['tentation', 'tenter', 'resister', 'addiction'],
    refs: [
      ['1 Corinthiens 10:13', 'Dieu ne permet pas au-delà de vos forces'],
      ['Matthieu 4:1',        'Jésus tenté au désert'],
      ['Matthieu 26:41',      'Veillez et priez pour ne pas entrer en tentation'],
      ['Jacques 1:12',        'Heureux l’homme qui supporte l’épreuve'],
      ['Hébreux 4:15',         'Tenté comme nous, sans commettre de péché'],
    ] },
  { t: 'Péché et repentir',
    kw: ['peche', 'pecheur', 'repentir', 'repentance', 'conversion', 'confession', 'se confesser', 'contrition'],
    refs: [
      ['1 Jean 1:9',          'Si nous confessons nos péchés, il pardonne'],
      ['Luc 15:7',            'Joie au ciel pour un seul pécheur qui se repent'],
      ['Psaumes 51:3',        'Aie pitié de moi, ô Dieu (Miserere)'],
      ['Isaïe 1:18',           'Vos péchés deviendront blancs comme neige'],
      ['Joël 2:12',           'Revenez à moi de tout votre cœur'],
      ['Actes des Apôtres 3:19',          'Repentez-vous et convertissez-vous'],
    ] },
  { t: 'Miséricorde',
    kw: ['misericorde', 'misericordieux', 'compassion', 'pitie'],
    refs: [
      ['Luc 6:36',            'Soyez miséricordieux comme votre Père'],
      ['Matthieu 5:7',        'Heureux les miséricordieux'],
      ['Psaumes 103:8',       'Lent à la colère, riche en bonté'],
      ['Éphésiens 2:4',        'Dieu, riche en miséricorde'],
      ['Luc 15:20',           'Le père, ému de compassion, courut'],
      ['Lamentations 3:22',   'Ses compassions ne sont pas à leur terme'],
    ] },
  { t: 'Juger les autres',
    kw: ['juger', 'jugement des autres', 'critique', 'critiquer', 'paille et poutre', 'medire'],
    refs: [
      ['Matthieu 7:1',        'Ne jugez point, afin de ne pas être jugés'],
      ['Matthieu 7:3',        'La paille et la poutre'],
      ['Jean 8:7',            'Que celui qui n’a jamais péché jette la pierre'],
      ['Luc 6:37',            'Ne condamnez point, et vous ne serez pas condamnés'],
      ['Romains 14:4',        'Qui es-tu pour juger le serviteur d’autrui ?'],
      ['Jacques 4:12',        'Un seul est législateur et juge'],
    ] },
  { t: 'Paroles et langue',
    kw: ['parole', 'langue', 'medisance', 'commerage', 'ragots', 'injure', 'bavardage'],
    refs: [
      ['Jacques 3:5',         'La langue, petit membre aux grands effets'],
      ['Proverbes 18:21',     'La mort et la vie au pouvoir de la langue'],
      ['Éphésiens 4:29',       'Qu’aucune parole mauvaise ne sorte'],
      ['Matthieu 12:36',      'Rendre compte de toute parole vaine'],
      ['Psaumes 141:3',       'Mets une garde à ma bouche'],
      ['Proverbes 15:1',      'Une réponse douce apaise'],
    ] },

  // ── Vie quotidienne & société ───────────────────────────
  { t: 'Argent et richesse',
    kw: ['argent', 'richesse', 'riche', 'avarice', 'cupidite', 'materialisme', 'dettes'],
    refs: [
      ['Matthieu 6:24',       'On ne peut servir Dieu et l’argent'],
      ['1 Timothée 6:10',     'L’amour de l’argent, racine de tous les maux'],
      ['Matthieu 6:19',       'Amassez des trésors dans le ciel'],
      ['Luc 12:15',           'Gardez-vous de toute avarice'],
      ['Marc 10:25',          'Le chameau et le trou de l’aiguille'],
      ['Ecclésiaste 5:9',     'Qui aime l’argent n’en est jamais rassasié'],
      ['Hébreux 13:5',         'Contentez-vous de ce que vous avez'],
    ] },
  { t: 'Pauvreté et les pauvres',
    kw: ['pauvrete', 'pauvre', 'misere', 'demunis', 'sdf', 'precarite'],
    refs: [
      ['Matthieu 25:40',      'Fait à l’un de ces plus petits, fait à moi'],
      ['Luc 4:18',            'Annoncer la bonne nouvelle aux pauvres'],
      ['Isaïe 58:7',           'Partage ton pain avec l’affamé'],
      ['Proverbes 19:17',     'Qui a pitié du pauvre prête à l’Éternel'],
      ['Luc 16:19',           'Le riche et le pauvre Lazare'],
      ['Deutéronome 15:11',   'Ouvre ta main à ton frère pauvre'],
      ['Jacques 2:5',         'Dieu a choisi les pauvres selon le monde'],
    ] },
  { t: 'Travail',
    kw: ['travail', 'travailler', 'metier', 'emploi', 'chomage', 'labeur', 'paresse'],
    refs: [
      ['Colossiens 3:23',     'Travaillez comme pour le Seigneur'],
      ['2 Thessaloniciens 3:10', 'Qui ne veut pas travailler ne mange pas non plus'],
      ['Genèse 2:15',         'Cultiver et garder le jardin'],
      ['Proverbes 14:23',     'Tout travail procure l’abondance'],
      ['Ecclésiaste 3:13',    'Jouir du bien-être au milieu de son travail'],
      ['Psaumes 128:2',       'Tu jouis du travail de tes mains'],
    ] },
  { t: 'Repos',
    kw: ['repos', 'se reposer', 'fatigue', 'epuisement', 'sabbat', 'burn out', 'sommeil'],
    refs: [
      ['Matthieu 11:28',      'Venez à moi… je vous donnerai du repos'],
      ['Genèse 2:2',          'Dieu se reposa le septième jour'],
      ['Psaumes 23:2',        'Il me fait reposer dans de verts pâturages'],
      ['Marc 6:31',           'Venez à l’écart et reposez-vous un peu'],
      ['Psaumes 127:2',       'Il en donne autant à ses bien-aimés pendant leur sommeil'],
      ['Exode 20:8',          'Souviens-toi du jour du repos'],
    ] },
  { t: 'Justice',
    kw: ['justice', 'juste', 'injustice', 'opprimes', 'droits'],
    refs: [
      ['Michée 6:8',           'Pratiquer la justice, aimer la miséricorde'],
      ['Amos 5:24',           'Que la droiture soit comme un torrent'],
      ['Isaïe 1:17',           'Apprenez à faire le bien, recherchez la justice'],
      ['Matthieu 5:6',        'Heureux les affamés de justice'],
      ['Proverbes 31:8',      'Ouvre ta bouche pour le muet'],
      ['Psaumes 82:3',        'Rendez justice au faible et à l’orphelin'],
    ] },
  { t: 'Paix',
    kw: ['paix', 'apaisement', 'serenite', 'calme'],
    refs: [
      ['Jean 14:27',          'Je vous laisse la paix, je vous donne ma paix'],
      ['Matthieu 5:9',        'Heureux ceux qui procurent la paix'],
      ['Philippiens 4:7',     'La paix de Dieu qui surpasse toute intelligence'],
      ['Isaïe 2:4',            'De leurs épées ils forgeront des socs'],
      ['Romains 12:18',       'S’il est possible, soyez en paix avec tous'],
      ['Psaumes 34:15',       'Recherche la paix et poursuis-la'],
    ] },
  { t: 'Guerre et violence',
    kw: ['guerre', 'violence', 'violent', 'conflit', 'arme'],
    refs: [
      ['Isaïe 2:4',            'On ne s’exercera plus à la guerre'],
      ['Matthieu 26:52',      'Remets ton épée à sa place'],
      ['Matthieu 5:39',       'Tendre l’autre joue'],
      ['Psaumes 46:10',       'Il fait cesser les combats'],
      ['Romains 12:19',       'Ne vous vengez point vous-mêmes'],
      ['Ecclésiaste 3:8',     'Un temps pour la guerre, un temps pour la paix'],
    ] },
  { t: 'Aimer ses ennemis',
    kw: ['ennemi', 'ennemis', 'vengeance', 'se venger', 'represailles', 'haine'],
    refs: [
      ['Matthieu 5:44',       'Aimez vos ennemis, priez pour eux'],
      ['Luc 6:27',            'Faites du bien à ceux qui vous haïssent'],
      ['Romains 12:20',       'Si ton ennemi a faim, donne-lui à manger'],
      ['Romains 12:14',       'Bénissez ceux qui vous persécutent'],
      ['Luc 23:34',           'Père, pardonne-leur'],
      ['Proverbes 25:21',     'Donne du pain à ton ennemi affamé'],
    ] },
  { t: 'Hospitalité et étrangers',
    kw: ['hospitalite', 'accueil', 'accueillir', 'etranger', 'migrant', 'refugie', 'immigre'],
    refs: [
      ['Hébreux 13:2',         'Certains ont logé des anges sans le savoir'],
      ['Matthieu 25:35',      'J’étais étranger et vous m’avez recueilli'],
      ['Lévitique 19:34',     'L’étranger sera pour vous comme l’un de vous'],
      ['Exode 23:9',          'Vous savez ce qu’éprouve l’étranger'],
      ['Romains 12:13',       'Exercez l’hospitalité'],
      ['1 Pierre 4:9',        'Hospitaliers, sans murmurer'],
    ] },
  { t: 'Autorités et politique',
    kw: ['autorite', 'gouvernement', 'politique', 'etat', 'cesar', 'impots', 'elections', 'president'],
    refs: [
      ['Matthieu 22:21',      'Rendez à César ce qui est à César'],
      ['Romains 13:1',        'Soumission aux autorités établies'],
      ['Actes des Apôtres 5:29',          'Obéir à Dieu plutôt qu’aux hommes'],
      ['1 Timothée 2:1',      'Prier pour tous ceux qui gouvernent'],
      ['1 Pierre 2:17',       'Honorez tout le monde, craignez Dieu'],
    ] },
  { t: 'Création et nature',
    kw: ['creation', 'nature', 'animaux', 'ecologie', 'environnement', 'terre', 'univers'],
    refs: [
      ['Genèse 1:1',          'Au commencement, Dieu créa'],
      ['Psaumes 19:2',        'Les cieux racontent la gloire de Dieu'],
      ['Psaumes 8:4',         'Quand je contemple les cieux…'],
      ['Genèse 2:15',         'Cultiver et garder la création'],
      ['Psaumes 104:24',      'Que tes œuvres sont en grand nombre !'],
      ['Romains 1:20',        'Ses perfections se voient dans ses œuvres'],
    ] },
  { t: 'Providence et soucis du lendemain',
    kw: ['providence', 'lendemain', 'soucis', 'inquiet', 'besoin', 'manque', 'confiance en la providence'],
    refs: [
      ['Matthieu 6:26',       'Regardez les oiseaux du ciel'],
      ['Matthieu 6:34',       'Ne vous inquietez pas du lendemain'],
      ['Philippiens 4:19',    'Dieu pourvoira à tous vos besoins'],
      ['Psaumes 37:5',        'Recommande ton sort à l’Éternel'],
      ['Proverbes 3:5',       'Confie-toi en l’Éternel'],
      ['Psaumes 55:23',       'Remets ton sort à l’Éternel'],
    ] },

  // ── Famille & relations ─────────────────────────────────
  { t: 'Mariage et couple',
    kw: ['mariage', 'se marier', 'epoux', 'epouse', 'couple', 'conjoint', 'fiancailles'],
    refs: [
      ['Genèse 2:24',         'Ils deviendront une seule chair'],
      ['Éphésiens 5:25',       'Maris, aimez vos femmes comme le Christ'],
      ['Marc 10:9',           'Que l’homme ne sépare pas ce que Dieu a uni'],
      ['Ecclésiaste 4:9',     'Deux valent mieux qu’un'],
      ['Cantique des Cantiques 8:7',        'Les grandes eaux ne peuvent éteindre l’amour'],
      ['1 Corinthiens 13:4',  'L’amour est patient… (lu aux mariages)'],
    ] },
  { t: 'Fidélité et adultère',
    kw: ['fidelite', 'infidelite', 'adultere', 'tromper', 'tentation conjugale'],
    refs: [
      ['Exode 20:14',         'Tu ne commettras point d’adultère'],
      ['Matthieu 5:27',       'L’adultère commence dans le regard'],
      ['Hébreux 13:4',         'Que le mariage soit honoré de tous'],
      ['Proverbes 5:18',      'Réjouis-toi de la femme de ta jeunesse'],
      ['Jean 8:7',            'La femme adultère : ni pierre, ni condamnation'],
    ] },
  { t: 'Divorce',
    kw: ['divorce', 'divorcer', 'separation', 'repudiation'],
    refs: [
      ['Marc 10:9',           'Ce que Dieu a uni…'],
      ['Matthieu 19:6',       'Ils ne sont plus deux, mais une seule chair'],
      ['Malachie 2:16',       'Je hais la répudiation, dit l’Éternel'],
      ['1 Corinthiens 7:10',  'Instructions de Paul aux époux'],
    ] },
  { t: 'Famille et parents',
    kw: ['famille', 'parents', 'pere', 'mere', 'honorer ses parents', 'education'],
    refs: [
      ['Exode 20:12',         'Honore ton père et ta mère'],
      ['Josué 24:15',         'Moi et ma maison, nous servirons l’Éternel'],
      ['Éphésiens 6:4',        'Parents, n’irritez pas vos enfants'],
      ['Proverbes 22:6',      'Instruis l’enfant selon la voie qu’il doit suivre'],
      ['Colossiens 3:20',     'Enfants, obéissez à vos parents'],
      ['1 Timothée 5:8',      'Prendre soin des siens'],
    ] },
  { t: 'Enfants',
    kw: ['enfant', 'enfants', 'bebe', 'naissance', 'petits'],
    refs: [
      ['Marc 10:14',          'Laissez venir à moi les petits enfants'],
      ['Psaumes 127:3',       'Les enfants, un héritage de l’Éternel'],
      ['Matthieu 18:3',       'Devenir comme des petits enfants'],
      ['Matthieu 18:10',      'Leurs anges voient la face du Père'],
      ['Deutéronome 6:7',     'Transmettre la foi à ses enfants'],
      ['Proverbes 22:6',      'Éduquer dès le plus jeune âge'],
    ] },
  { t: 'Vieillesse',
    kw: ['vieillesse', 'vieillir', 'vieux', 'personnes agees', 'cheveux blancs', 'grand age', 'retraite'],
    refs: [
      ['Isaïe 46:4',           'Jusqu’à votre vieillesse, je vous porterai'],
      ['Psaumes 92:15',       'Ils portent encore des fruits dans la vieillesse'],
      ['Proverbes 16:31',     'Les cheveux blancs, une couronne d’honneur'],
      ['Lévitique 19:32',     'Lève-toi devant les cheveux blancs'],
      ['Psaumes 71:9',        'Ne me rejette pas au temps de la vieillesse'],
      ['2 Corinthiens 4:16',  'L’homme intérieur se renouvelle de jour en jour'],
    ] },
  { t: 'Jeunesse',
    kw: ['jeunesse', 'jeunes', 'adolescent', 'ado', 'etudiant'],
    refs: [
      ['Ecclésiaste 12:1',    'Souviens-toi de ton Créateur aux jours de ta jeunesse'],
      ['1 Timothée 4:12',     'Que personne ne méprise ta jeunesse'],
      ['Psaumes 119:9',       'Comment le jeune homme gardera-t-il pur son chemin ?'],
      ['Lamentations 3:27',   'Il est bon de porter le joug dès sa jeunesse'],
      ['Proverbes 20:29',     'La force est la gloire des jeunes gens'],
    ] },
  { t: 'Amitié',
    kw: ['amitie', 'ami', 'amis', 'copain', 'fraternite'],
    refs: [
      ['Proverbes 17:17',     'L’ami aime en tout temps'],
      ['Jean 15:13',          'Donner sa vie pour ses amis'],
      ['Jean 15:15',          'Je vous appelle mes amis'],
      ['Proverbes 27:17',     'Le fer aiguise le fer'],
      ['Ecclésiaste 4:10',    'Malheur à celui qui tombe seul'],
      ['1 Samuel 18:1',       'David et Jonathan, amitié exemplaire'],
    ] },
  { t: 'Unité et communauté',
    kw: ['unite', 'communaute', 'ensemble', 'eglise', 'division', 'communion fraternelle'],
    refs: [
      ['Psaumes 133:1',       'Qu’il est doux pour des frères d’être ensemble'],
      ['Jean 17:21',          'Que tous soient un'],
      ['1 Corinthiens 12:12', 'Un seul corps, plusieurs membres'],
      ['Actes des Apôtres 2:44',          'La vie de la première communauté'],
      ['Éphésiens 4:3',        'Conserver l’unité de l’Esprit'],
      ['Colossiens 3:14',     'L’amour, lien de la perfection'],
    ] },

  // ── Corps, pureté, sobriété ─────────────────────────────
  { t: 'Pureté et chasteté',
    kw: ['purete', 'pur', 'chastete', 'sexualite', 'luxure', 'pornographie', 'corps'],
    refs: [
      ['Matthieu 5:8',        'Heureux ceux qui ont le cœur pur'],
      ['1 Corinthiens 6:19',  'Votre corps est le temple du Saint-Esprit'],
      ['Psaumes 51:12',       'Crée en moi un cœur pur, ô Dieu'],
      ['Philippiens 4:8',     'Tout ce qui est pur… qu’il occupe vos pensées'],
      ['1 Thessaloniciens 4:3', 'La volonté de Dieu : votre sanctification'],
      ['2 Timothée 2:22',     'Fuis les passions de la jeunesse'],
    ] },
  { t: 'Alcool et sobriété',
    kw: ['alcool', 'alcoolisme', 'ivresse', 'ivrogne', 'boire', 'sobriete', 'drogue', 'dependance'],
    refs: [
      ['Éphésiens 5:18',       'Ne vous enivrez pas de vin'],
      ['Proverbes 20:1',      'Le vin est moqueur'],
      ['Proverbes 23:29',     'Pour qui les gémissements ? Pour qui les plaies ?'],
      ['1 Pierre 5:8',        'Soyez sobres, veillez'],
      ['Galates 5:22',        'La maîtrise de soi, fruit de l’Esprit'],
      ['1 Corinthiens 6:12',  'Tout m’est permis, mais je ne me laisserai pas asservir'],
    ] },

  // ── Sacrements & vie de foi ─────────────────────────────
  { t: 'Baptême',
    kw: ['bapteme', 'baptiser', 'baptise'],
    refs: [
      ['Matthieu 28:19',      'Allez, baptisez toutes les nations'],
      ['Marc 1:9',            'Le baptême de Jésus au Jourdain'],
      ['Actes des Apôtres 2:38',          'Repentez-vous et soyez baptisés'],
      ['Romains 6:4',         'Ensevelis avec lui par le baptême'],
      ['Jean 3:5',            'Naître d’eau et d’Esprit'],
      ['Galates 3:27',        'Baptisés en Christ, revêtus de Christ'],
    ] },
  { t: 'Eucharistie et communion',
    kw: ['eucharistie', 'communion', 'communier', 'hostie', 'pain de vie', 'messe', 'cene'],
    refs: [
      ['Matthieu 26:26',      'Ceci est mon corps (institution)'],
      ['Jean 6:51',           'Je suis le pain vivant descendu du ciel'],
      ['1 Corinthiens 11:23', 'Faites ceci en mémoire de moi'],
      ['Luc 24:30',           'Reconnu à la fraction du pain (Emmaüs)'],
      ['Jean 6:35',           'Je suis le pain de vie'],
      ['Actes des Apôtres 2:42',          'Ils étaient assidus à la fraction du pain'],
    ] },
  { t: 'Jeûne',
    kw: ['jeuner', 'jeune alimentaire', 'careme', 'penitence', 'privation'],
    refs: [
      ['Matthieu 6:16',       'Quand vous jeûnez, sans le montrer'],
      ['Isaïe 58:6',           'Le jeûne que Dieu préfère'],
      ['Joël 2:12',           'Revenez à moi avec jeûnes et larmes'],
      ['Matthieu 4:2',        'Jésus jeûne 40 jours au désert'],
      ['Actes des Apôtres 13:2',          'Pendant qu’ils jeûnaient et priaient'],
    ] },
  { t: 'Esprit Saint',
    kw: ['esprit saint', 'saint esprit', 'pentecote', 'dons de l esprit', 'consolateur'],
    refs: [
      ['Actes des Apôtres 2:4',           'Tous remplis du Saint-Esprit (Pentecôte)'],
      ['Jean 14:26',          'Le Consolateur vous enseignera toutes choses'],
      ['Galates 5:22',        'Le fruit de l’Esprit'],
      ['Romains 8:26',        'L’Esprit intercède par des soupirs'],
      ['1 Corinthiens 12:4',  'Diversité de dons, même Esprit'],
      ['Actes des Apôtres 1:8',           'Vous recevrez une puissance'],
    ] },
  { t: 'Marie, mère de Jésus',
    kw: ['marie', 'vierge marie', 'sainte vierge', 'annonciation', 'magnificat'],
    refs: [
      ['Luc 1:26',            'L’Annonciation à Marie'],
      ['Luc 1:42',            'Bénie entre les femmes'],
      ['Luc 1:46',            'Le Magnificat'],
      ['Jean 2:5',            'Faites tout ce qu’il vous dira (Cana)'],
      ['Jean 19:26',          'Voici ta mère (au pied de la croix)'],
      ['Luc 2:19',            'Marie gardait toutes ces choses en son cœur'],
    ] },
  { t: 'Anges',
    kw: ['ange', 'anges', 'ange gardien', 'archange'],
    refs: [
      ['Psaumes 91:11',       'Il ordonnera à ses anges de te garder'],
      ['Matthieu 18:10',      'Leurs anges voient la face du Père'],
      ['Hébreux 13:2',         'Loger des anges sans le savoir'],
      ['Luc 1:26',            'L’ange Gabriel envoyé à Marie'],
      ['Psaumes 34:8',        'L’ange de l’Éternel campe autour des fidèles'],
      ['Hébreux 1:14',         'Esprits au service de Dieu'],
    ] },
  { t: 'Salut et grâce',
    kw: ['salut', 'sauver', 'grace', 'redemption', 'sauveur'],
    refs: [
      ['Éphésiens 2:8',        'C’est par la grâce que vous êtes sauvés'],
      ['Jean 3:16',           'Dieu a tant aimé le monde'],
      ['Romains 10:9',        'Confesser Jésus, croire en son cœur'],
      ['Romains 5:8',         'Christ est mort pour nous, pécheurs'],
      ['Actes des Apôtres 4:12',          'Aucun autre nom pour être sauvés'],
      ['Tite 3:5',            'Sauvés selon sa miséricorde'],
    ] },
  { t: 'Vie éternelle et ciel',
    kw: ['vie eternelle', 'ciel', 'paradis', 'eternite', 'au dela', 'resurrection'],
    refs: [
      ['Jean 14:2',           'Il y a plusieurs demeures chez mon Père'],
      ['Jean 11:25',          'Je suis la résurrection et la vie'],
      ['1 Corinthiens 2:9',   'Ce que l’œil n’a pas vu…'],
      ['Apocalypse 21:1',     'Un ciel nouveau et une terre nouvelle'],
      ['1 Corinthiens 15:55', 'Mort, où est ta victoire ?'],
      ['Philippiens 3:20',    'Notre cité à nous est dans les cieux'],
    ] },
  { t: 'Commandements et Parole de Dieu',
    kw: ['commandement', 'commandements', 'loi de dieu', 'decalogue', 'parole de dieu', 'ecriture'],
    refs: [
      ['Exode 20:1',          'Les Dix Commandements'],
      ['Deutéronome 6:5',     'Tu aimeras l’Éternel de tout ton cœur'],
      ['Matthieu 22:37',      'Le plus grand commandement'],
      ['Jean 14:15',          'Si vous m’aimez, gardez mes commandements'],
      ['Psaumes 119:105',     'Ta parole, une lampe à mes pieds'],
      ['Jean 13:34',          'Le commandement nouveau'],
    ] },
  { t: 'Vocation et appel de Dieu',
    kw: ['vocation', 'appel', 'appele', 'suivre jesus', 'disciple', 'mission'],
    refs: [
      ['1 Samuel 3:10',       'Parle, ton serviteur écoute'],
      ['Isaïe 6:8',            'Me voici, envoie-moi'],
      ['Matthieu 4:19',       'Je vous ferai pêcheurs d’hommes'],
      ['Jérémie 1:5',          'Consacré avant la naissance'],
      ['Marc 10:21',          'Viens et suis-moi'],
      ['Jean 15:16',          'C’est moi qui vous ai choisis'],
    ] },
  { t: 'Persécution des chrétiens',
    kw: ['persecution', 'persecute', 'martyr', 'chretiens persecutes', 'moquerie de la foi'],
    refs: [
      ['Matthieu 5:10',       'Heureux les persécutés pour la justice'],
      ['Jean 15:20',          'S’ils m’ont persécuté, ils vous persécuteront'],
      ['Romains 8:35',        'Qui nous séparera de l’amour du Christ ?'],
      ['2 Timothée 3:12',     'Vivre pieusement attire la persécution'],
      ['1 Pierre 4:14',       'Heureux si l’on vous outrage pour Christ'],
      ['Matthieu 10:28',      'Ne craignez pas ceux qui tuent le corps'],
    ] },
];
